### PR TITLE
feat: compute cursor for each result

### LINKED ISSUE #156: [Feature Proposal] Compute cursor for each document
**Feature request & proposal**

Highlighting the relay [specification](https://relay.dev/docs/en/graphql-server-specification.html#connections) for the cursor based pagination which specifies a cursor for each document. As things are today, this library returns pagination metadata as separate fields (`next`, `previous`, etc..) which points to the last document of the list. 

I propose to add an additional field `_cursor` for each document which will allow the user to move in forward/backward direction from any node in a list. 

Example - 

```json

{
 "results":
   [ 
      { 
        " _id" : "580fd16aca2a6b271562d8bb", 
        "counter": 4, 
        "_cursor": "eyIkb2lkIjoiNTgwZmQxNmFjYTJhNmIyNzE1NjJkOGJiIn0" },
      {
       " _id": "580fd16aca2a6b271562d8ba",
       "counter": 3, 
        "_cursor": "eyIkb2lkIjoiNTgwZmQxNmFjYTJhNmIyNzE1NjJkOGJhIn0" 
      } 
  ],
  "next": "eyIkb2lkIjoiNTgwZmQxNmFjYTJhNmIyNzE1NjJkOGJhIn0",
  "hasNext": "true" 
}

### PR DESCRIPTION
**Pull request by ayrtonvwf**
#### Changes Made
- Move cursor computing logic to functions on a new file under the utils folder.
- Add the includeCursor opt-in param.
- Compute cursor for each result (resolves #156) based on the includeCursor param.

#### Potential Risks
Not fully understanding all the uses of the paginatedField, I just isolated and exctracted the cursor creation logic from existing code I found on this library. If something I didn't predict is passed in the `paginatedField` value, the cursor validity would be compromised. The good thing is that the new centralized approach handles the cursor logic isolatedly so this event would be easier to spot and fix.

#### Test Plan
- Existing code using this library shouldn't see any changes.
- By passing the new `includeCursor` parameter, the response should include a `_cursor` property for each document, containing the document cursor.
- The first document cursor should be equal to the `previous` result property.
- The last document cursor should be equal to the `next` result property.
- Being the result empty, the `previous` and `next` results should be `null`.

#### Checklist
- [ ] I've increased test coverage
- [ ] Since this is a public repository, I've checked I'm not publishing private data in the code, commit comments, or this PR.

### CODE REVIEW

**Comment by bradvogel** [comment]
@ayrtonvwf are you still working on this?

**Comment by ayrtonvwf** [comment]
> @ayrtonvwf are you still working on this?

It's implemented but as I was not able to run the automated tests in my computer (some error with the test tooling I couldn't figure out) I'm not able to finish this PR, but I guess it's only a matter of updating the tests and making them pass.

**Comment by christiansany** [comment]
Helloooo :)
When will this be merged? Any plans/timeline?

**Comment by bradvogel** [comment]
Someone just needs to finish it and write tests.

**Comment by bradvogel** [comment]
Closing due to age. Let me know if you'd like to reopen

**Pull request closed without merging**
