### PR TITLE
Feature/fix conflict files and add tests

### LINKED ISSUE #236: Allow user to restrict fields to return when using mongoose
By default, queries in MongoDB return all fields in matching documents. To limit the amount of data that MongoDB sends to applications, you can include a projection document to specify or restrict fields to return.

### Issue

using `params.fields` does nothing and all fields is returned in matching documents.

### Expected
```
 it('returns data with expected fields', async () => {
    const data = await Post.paginate({ fields: { title: 1 }, limit: 1 });
    const [post] = data.results;
    expect(post.title).toBeTruthy();
    expect(post.date).toBeFalsy();
    expect(post.author).toBeFalsy();
    expect(post.body).toBeFalsy();
  });
```
The following test failed.

This PR seems to solve the issue : 
https://github.com/mixmaxhq/mongo-cursor-pagination/pull/60

Please make a review if possible

### PR DESCRIPTION
**Pull request by OlivierAlbertini**
#### Changes Made
Hi,

I forked @Gastonite repo https://github.com/Gastonite/mongo-cursor-pagination
I fixed conflicting files from https://github.com/mixmaxhq/mongo-cursor-pagination/pull/60
closes #236

#### Potential Risks
Potential risks are limited since its covered by tests.

#### Test Plan
I added tests in order to show that projection works.

Since there is no ci,
Here I show that all tests passed:

Capture d’écran, le 2020-09-22 à 10 11 00
Capture d’écran, le 2020-09-22 à 10 10 48

#### Checklist
- [x] I've increased test coverage
- [x] Since this is a public repository, I've checked I'm not publishing private data in the code, commit comments, or this PR.

Please let me know if I can help in anything

### CODE REVIEW

**Comment by mchockal** [comment]
@OlivierAlbertini  : This PR hasn't been merged yet, if I'm not wrong?
The sadness .. :( I'm currently working with a workaround for now. 
Could this be merged anytime soon?

**Comment by bradvogel** [comment]
This hasn't been merged yet. I needs to be rebased on the latest master

**Comment by OlivierAlbertini** [comment]
> This hasn't been merged yet. I needs to be rebased on the latest master

done!

**Comment by OlivierAlbertini** [comment]
> @OlivierAlbertini : This PR hasn't been merged yet, if I'm not wrong?
> The sadness .. :( I'm currently working with a workaround for now.
> Could this be merged anytime soon?

I still hope =)

**Comment by bradvogel** [comment]
I'm getting test failures in this branch. My commands:

```
git checkout -b OlivierAlbertini-feature/fix-conflict-files-and-add-tests master
git pull https://github.com/OlivierAlbertini/mongo-cursor-pagination.git feature/fix-conflict-files-and-add-tests
npm ci
npm test
```

image

**Comment by OlivierAlbertini** [comment]
> I'm getting test failures in this branch. My commands:
> 
> ```
> git checkout -b OlivierAlbertini-feature/fix-conflict-files-and-add-tests master
> git pull https://github.com/OlivierAlbertini/mongo-cursor-pagination.git feature/fix-conflict-files-and-add-tests
> npm ci
> npm test
> ```
> 
> image

Thanks I'm able to reproduce with fresh install, seems related to the rebase (new package versions)
I will check this when I will have some bandwidth

**Comment by bradvogel** [comment]
Closing due to age. Let me know if you'd like to reopen

**Pull request closed without merging**
