### PR TITLE
use version 3 of the MongoDB API

### PR DESCRIPTION
**Pull request by Gastonite**
Hi!
first, this library is a good thing, thank you!

I was wondering why not use mongodb api v3, so i tried to do something =)

### CODE REVIEW

**Comment by tchambard** [comment]
Hello, I'm really interested by this pull request (because it solves NOT WORKING projection when using mongodb client v3).

Is there a reason for this PR still not be merged ?

**Comment by skeggse** [comment]
>Is there a reason for this PR still not be merged ?

At the very least, it would need to have its conflicts resolved.

Beyond that, it's very time-consuming to maintain open-source repositories. As a maintainer, it often happens that you look for the low-hanging fruit and focus on that. This often means looking at PRs that are narrow in scope, that you have a lot of context on, or that have clearly defined and well-reasoned test plans.

This is a relatively big change in a tool that we don't use very often. We don't have any working knowledge/experience with mongoose (community-added feature), so we can't easily review those changes. The test changes look valuable, yet without a clear test plan and risk analysis in the original PR description, it's difficult to evaluate the completeness and impact of this change without spending a lot of time on it. (Yes, this is a big wall of text, but it only took me three minutes to type out - not trying to call out @Gastonite, just wanted to share about our processes and the reason behind many PRs languishing.) As always, community support is welcome and encouraged - add a review, even if it's just commenting on the ways that the change makes sense and looks good to you!

**Comment by Gastonite** [comment]
Yes, it's time-consuming to maintain a library, thank you for your work!

I understand that we can be cautious when we have (probably important) applications that use this library, but we do not make an omelet without breaking eggs. For the use I have of this library, I see no risks, the tests are quite good.

"We don't have any working knowledge/experience with mongoose"

Me neither, but just a question: why did you allow support in your library for something you don't have knowlege on, instead of inciting to create another package specially dedicated to Mongoose which would maybe depend of "mongo-cursor-pagination"?

Perhaps, the persons who have added the mongoose support could help here?

When I created this PR, no one took even 2 minutes to just comment on how the change made sense. But the commits continued.

I have merge all changes since december, hope this initally little PR will be reviewed.

**Comment by OlivierAlbertini** [comment]
I was making the same PR.... and I saw yours xD

So I would add a test in order to show what it solve : 

Inside `mongoosePlugin.test.js`

``` 
 it('returns data with expected fields', async () => {
    const data = await Post.paginate({ fields: { title: 1 }, limit: 1 });
    const [post] = data.results;
    expect(post.title).toBeTruthy();
    expect(post.date).toBeFalsy();
    expect(post.author).toBeFalsy();
    expect(post.body).toBeFalsy();
  });
```

I do you have some bandwidth for fixing conflicting files ?
Also I'm wondering why it's not merged...

**Comment by Gastonite** [comment]
Normally I would say YESSSS, but since the author doesn't have the bandwidth to give me an answer, I also don't have any bandwidth for his library, really sorry ...

If you are ok with my fork, maybe we could try to publish something else?

**Comment by OlivierAlbertini** [comment]
> Normally I would say YESSSS, but since the author doesn't have the bandwidth to give me an answer, I also don't have any bandwidth for his library, really sorry ...

No problem. I made this PR from your fork: https://github.com/mixmaxhq/mongo-cursor-pagination/pull/239

**Comment by bradvogel** [comment]
Closing due to age.

**Pull request closed without merging**
