### PR TITLE
Support for native MongoDB driver

### PR DESCRIPTION
**Pull request by lirbank**
This PRs makes the package work with the native MongoDB Node.js driver, as well as with mongoist.

The tests pass but I’ve not added any new to test with the native driver. Hope that’s OK?

### CODE REVIEW

**Comment by bradvogel** [comment]
can you add a unit test?

**Comment by ghmeier** [comment]
One potential problem I see with this is that it will provide unexpected results if the [`manofish/mongojs`](https://github.com/mafintosh/mongojs) driver is provided since the instance of `find` there expects a callback.

**Comment by gastonelhordoy** [comment]
The callback is actually optional. Check the [function return type](https://github.com/mongodb/node-mongodb-native/blob/65946a92cd0f82edb464a28fe7ce08945b9b8c74/lib/collection.js#L231) and and [code handling the missing callback](https://github.com/mongodb/node-mongodb-native/blob/65946a92cd0f82edb464a28fe7ce08945b9b8c74/lib/collection.js#L375).

**Comment by lirbank** [comment]
@ghmeier is manofish/mongojs a supported driver? I was under the impression only mongoist was supported. Wouldn't it be sufficient to update the README and point out the supported drivers (mongoist and native mongodb (with this PR))?

@bradvogel will update with unit tests soon (hopefully tomorrow).

**Comment by lirbank** [comment]
Ok, I've added tests and updated the README that the native driver is supported. Have a look and let me know if anything else is needed.

WRT the tests, I had some issues with looping the tests through both drivers. I couldn't manage to get the concurrency to operate correctly, so the tests where not reliably running with the correct driver (the driver was replaced in the `before` section before the tests had completed, stuff like that). Instead of spending more time on it I decided to just run the whole test suite two times, one for each driver, as you can see in package.json. Hope that's ok.

**Comment by bradvogel** [comment]
Great thanks! Will review in the next 2days. Sorry for the delay

**Comment by bradvogel** [comment]
Thanks! Released as 6.1.0.

**Pull request merged**
